apiVersion: v1
kind: Namespace
metadata:
  name: gofr-demo
  labels:
    app.kubernetes.io/name: gofr-demo
    app.kubernetes.io/part-of: cloud-native-platform-demo
    app.kubernetes.io/managed-by: make
